#include "stdio.h"
void main(){
	int a[4]={56,65,54,45},b[4]={57,76,56,67},c[4]={34,54,56,65},d[4]={43,45,56,65},e[4]={34,56,76,78},f[4],sum=0,i,j,x;
	printf("第一个同学的成绩为");
	for(i=0;i<4;i++){
		printf("%d\t",a[i]);
		sum=sum+a[i];
	}
	f[0]=sum/4;
	printf("平均成绩为：%d\n",sum/4);
	sum=0;
	printf("第二个同学的成绩为");
	for(i=0;i<4;i++){
		printf("%d\t",b[i]);
		sum=sum+b[i];
	}
	f[1]=sum/4;
	printf("平均成绩为：%d\n",sum/4);	
	sum=0;
	printf("第三个同学的成绩为");
	for(i=0;i<4;i++){
		printf("%d\t",c[i]);
		sum=sum+c[i];
	}
	f[2]=sum/4;
	printf("平均成绩为：%d\n",sum/4);	
	sum=0;
	printf("第四个同学的成绩为");
	for(i=0;i<4;i++){
		printf("%d\t",d[i]);
		sum=sum+d[i];
	}
	f[3]=sum/4;
	printf("平均成绩为：%d\n",sum/4);	
	sum=0;
	printf("第五个同学的成绩为");
	for(i=0;i<4;i++){
		printf("%d\t",e[i]);
		sum=sum+e[i];
	}
	printf("平均成绩为：%d\n",sum/4);
	f[4]=sum/4;
	for(i=0;i<4;i++){
		for(j=i+1;j<4;j++){
			if(f[i]<f[j]){
				x=f[j];
				f[j]=f[i];
				f[i]=x;
			}
		}
	}
	printf("5位同学的平均成绩从大到小的排序为：");
	for(i=0;i<4;i++){
		printf("%d\t",f[i]);
	}
}