select * from classes
select * from elements
select * from hourse
select * from student
select * from says
select * from score
select * from projectf
select * from defenses
select * from summary
select * from job
select * from Application
select * from leave
select * from sback
