# Project: 1.Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 607平均数2.o
LINKOBJ  = 607平均数2.o
LIBS     = -L"E:/professionalstudy/Dev-Cpp/MinGW64/lib" -L"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 1.Project.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

607平均数2.o: 607平均数2.cpp
	$(CPP) -c 607平均数2.cpp -o 607平均数2.o $(CXXFLAGS)
